language: java
jdk: openjdk10
install: true
addons:
  sonarcloud:
    organization: "jheinzde-github"
    token:
      secure: SONAR_TOKEN
script: ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - $HOME/.m2